In [2]:
import pandas as pd 
df = pd.read_csv("ventas_corruptas.csv")
df.head(10)

,ID_Venta,ID_Cliente,Region,Categoria,Unidades_Vendidas,Precio_Unitario,Ingresos,Ganancia,Fecha
0,247,2196.0,Sur,Belleza,18.0,139.92,2518.56,503.70,2025-07-24
1,303,2090.0,Norte,Hogar,2.0,812.84,1625.68,554.08,2025-06-01
2,156,2187.0,Norte,Hogar,16.0,784.20,12547.20,4954.74,2025-08-02
3,296,2039.0,Centro,Deportes,1.0,420.59,420.59,82.21,2025-07-26
4,212,2123.0,Centro,Hogar,7.0,91.58,641.06,123.90,2025-01-09
5,196,2073.0,Este,Ropa,5.0,2265.69,11328.45,2705.95,2025-08-07
6,181,2129.0,Sur,Ropa,4.0,288.28,1153.12,556.92,2025-08-16
7,316,2077.0,Norte,Electronica,14.0,1675.35,23454.90,10559.42,2025-04-30
8,324,2100.0,Sur,Hogar,13.0,1448.47,18830.11,4556.83,2025-06-08
9,328,2093.0,Sur,Hogar,14.0,123.60,1730.40,590.80,2025-03-14

1.Explorar Dataset
2.Encontrar un patrón
3.Encontrar una anomalía 
4.Encontrar una relación
5.Crear una evidencia visual
6.Presentar una conclusión

In [3]:
df.shape

(370, 9)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 370 entries, 0 to 369
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID_Venta           370 non-null    int64
 1   ID_Cliente         354 non-null    float64
 2   Region             370 non-null    str
 3   Categoria          370 non-null    str
 4   Unidades_Vendidas  342 non-null    float64
 5   Precio_Unitario    370 non-null    float64
 6   Ingresos           342 non-null    float64
 7   Ganancia           342 non-null    float64
 8   Fecha              370 non-null    str
dtypes: float64(5), int64(1), str(3)
memory usage: 26.1 KB

In [5]:
df.isnull().sum()

ID_Venta              0
ID_Cliente           16
Region                0
Categoria             0
Unidades_Vendidas    28
Precio_Unitario       0
Ingresos             28
Ganancia             28
Fecha                 0
dtype: int64

In [6]:
df.describe()

,ID_Venta,ID_Cliente,Unidades_Vendidas,Precio_Unitario,Ingresos,Ganancia
count,370.000000,354.000000,342.000000,370.00000,342.000000,342.000000
mean,174.486486,2096.022599,9.476608,1542.81300,14706.892544,4903.555526
std,100.994572,57.601292,5.486136,863.88265,12460.975027,4533.534232
min,1.000000,2000.000000,1.000000,59.03000,110.090000,44.250000
25%,86.250000,2049.000000,5.000000,785.01500,4617.135000,1449.260000
50%,175.500000,2096.000000,9.000000,1580.09000,11578.800000,3385.640000
75%,260.750000,2145.000000,14.000000,2313.83500,22780.770000,7325.747500
max,350.000000,2199.000000,19.000000,2994.86000,51325.560000,21453.940000

Se realizará un agrupado por región para coonocer cuantas regiones tenemos

In [9]:
agrupado_region = df.groupby("Region").agg({"Unidades_Vendidas": "sum"})
agrupado_region

         Unidades_Vendidas
Region
 Centro               14.0
 norte                 0.0
Centro               631.0
Este                 635.0
Norte                562.0
Norte                  0.0
OESTE                 67.0
Oeste                531.0
SUR                   56.0
Sur                  666.0
centro                35.0
este                  25.0
sur                   19.0

Al ejecutarlo encontramos que nuestras regiones viene separadas, debido a la modificacion por máyusculas y minúsculas, por lo que haremos la modificación para que python realicé una mejor agrupación

In [12]:
df["Region"] = df["Region"].str.strip()  # Elimina espacios al inicio y al final
df["Region"] = df["Region"].str.title()  #Convierte la primera letra de cada palabra a mayúscula y el resto a minúscula
agrupado_region = df.groupby("Region", as_index=True)["Unidades_Vendidas"].sum()
agrupado_region

Region
Centro    680.0
Este      660.0
Norte     562.0
Oeste     598.0
Sur       741.0
Name: Unidades_Vendidas, dtype: float64

In [ ]:
#Agrupado por categoria para conocer que tipo de categorias tenemos
agrupado_categoria = df.groupby("Categoria", as_index=True)["Unidades_Vendidas"].sum()
agrupado_categoria

Categoria
Belleza        607.0
Deportes       705.0
Electronica    608.0
Hogar          667.0
Ropa           654.0
Name: Unidades_Vendidas, dtype: float64

In [14]:
#Ahora como existen valores nulos, vamos analizar si vienen por alguna region en especifico
agrupado_nulos = df.groupby("Region").apply(lambda x: x.isnull().sum())
agrupado_nulos

,ID_Venta,ID_Cliente,Categoria,Unidades_Vendidas,Precio_Unitario,Ingresos,Ganancia,Fecha
Region,,,,,,,,
Centro,0,5,0,3,0,3,3,0
Este,0,5,0,7,0,7,7,0
Norte,0,2,0,6,0,6,6,0
Oeste,0,1,0,9,0,9,9,0
Sur,0,3,0,3,0,3,3,0

In [15]:
#Ahora como existen valores nulos, vamos analizar si vienen por alguna categoria en especifico
agrupado_categoria_nulos = df.groupby("Categoria").apply(lambda x: x.isnull().sum())
agrupado_categoria_nulos

,ID_Venta,ID_Cliente,Region,Unidades_Vendidas,Precio_Unitario,Ingresos,Ganancia,Fecha
Categoria,,,,,,,,
Belleza,0,1,0,1,0,1,1,0
Deportes,0,3,0,5,0,5,5,0
Electronica,0,4,0,3,0,3,3,0
Hogar,0,4,0,9,0,9,9,0
Ropa,0,4,0,10,0,10,10,0

---------- Reto ---------------
Una pregunta
Una hipotesis 
Una estadistica 
Una gráfica 
Un hallazgo
Una anomalía 
Una conclusión